apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ parameters.name }}
  description: ${{ parameters.description }}
  links:
    - title: Open build pipeline
      url: ${{ steps.azdevops.output.pipelineUrl }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: '${{ parameters.name }}.funda.io'
    dev.azure.com/project: ${{ parameters.owner }}
    dev.azure.com/build-definition: ${{ default(steps.azdevops.output.buildPipelineId, '') | string }}
spec:
  type: api
  lifecycle: experimental
  owner: ${{ parameters.owner }}
  name: ${{ parameters.name }}
