apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: api
  lifecycle: experimental
  owner: ${{ values.owner }}
  name: ${{ values.name }}
