apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ parameters.name or values.name }}
  description: ${{ parameters.description or values.description }}
  tags:
    - service
  links:
    - title: Open build pipeline
      url: ${{ steps.azdevops.output.pipelineUrl | default('http://dummy.invalid/') | string }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: 'Funda.${{ parameters.name or values.name }}'
spec:
  type: api
  lifecycle: experimental
  owner: ${{ parameters.owner or values.owner }}
  name: ${{ parameters.name or values.name }}
