apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Backstage-template-test
  description: Templating test
spec:
  owner: Team Platform
  type: template-test
  parameters:
    - title: What is the test value?
      description: Enter the test value.
      type: object
      required:
        - testValue
      properties:
        testValue:
          type: string
          title: Test value
    - title: Owner
      description: Owner
      properties:        
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            # Here's the option you can pass to the RepoUrlPicker
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                  - workflow:write
            allowedHosts:
              - github.com
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          testValue: ${{ parameters.testValue }}
          owner: ${{ parameters.owner }}
  
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: THhs is ${{ parameters.testValue }}
        repoUrl: ${{ parameters.repoUrl }} # 'github.com?owner=phaakmat&repo=backstage-template-test.${{ parameters.testValue }}'
        token: ${{ secrets.USER_OAUTH_TOKEN }}
