apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet-feature-api
  title: .NET 6.0 Feature API
  description: Create a .NET 6.0 Feature API
spec:
  owner: Team Platform
  type: api
  parameters:
    - title: Enter values
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Name
          type: string
          pattern: ^[a-z][a-z0-9]+$
          description: Unique name of the Feature API. Should be a single word.
          minLength: 5
          maxLength: 30
          ui:autoFocus: true
        description:
          title: Description
          type: string
          description: Description of the Feature API.
          minLength: 5
          maxLength: 300
          ui:options:
            rows: 3
          ui:widget: textarea
        owner:
          title: Owner
          type: string
          description: Owner of the package
          ui:field: OwnerPicker
          ui:widget: select
          ui:options:
            allowedKinds:
              - Group

  # scaffolding steps
  steps:
    - id: fetch-base
      name: Fetch Template
      action: fetch:template
      input:
        url: './template'
        values:
          name: ${{ parameters.name }}
          repoName: '${{ parameters.name }}.funda.io'
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        defaultBranch: main
        description: ${{ parameters.description }}
        repoUrl: 'github.com?owner=phaakmat&repo=${{ parameters.name }}.funda.io'

    - id: azdevops
      name: Create AzureDevOps Pipeline
      action: azdevops-pipeline-creator
      input:
        owner: ${{ parameters.owner }}
        name: '${{ parameters.name }}.funda.io'

    - id: updateCatalogInfo
      name: Update catalog-info.yaml with AZ Pipeline info
      action: catalog:write
      input:
        entity:
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: ${{ parameters.name }}
            description: ${{ parameters.description }}
            links:
              - title: Open build pipeline
                url: ${{ steps.azdevops.output.pipelineUrl }}
            annotations:
              backstage.io/techdocs-ref: dir:.
              github.com/project-slug: ${{ parameters.repoName }}
              dev.azure.com/project: ${{ parameters.owner }}
              dev.azure.com/build-definition: ${{ steps.azdevops.output.buildPipelineId | string }}
          spec:
            type: api
            lifecycle: experimental
            owner: ${{ parameters.owner }}
            name: ${{ parameters.name }}

    - id: makepr
      name: Make PR
      action: publish:github:pull-request
      input:
        description: ${{ parameters.description }}
        repoUrl: 'github.com?owner=phaakmat&repo=${{ parameters.name }}.funda.io'
        branchName: catalog-info
        title: "Update catalog-info.yaml"

    - id: register
      name: Register with Backstage
      action: catalog:register
      input:
        catalogInfoUrl: '${{ steps.publish.output.repoContentsUrl }}/catalog-info.yaml'

    - id: debug
      name: Debug Pipeline Outputs
      action: debug:log
      input:
        message: "pipelineUrl=${{ steps.azdevops.output.pipelineUrl }}"

  # outputs
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
      - title: Finish PR
        url: ${{ steps.makepr.output.remoteUrl }}
