apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet-feature-api
  title: .NET 6.0 Feature API
  description: Create a .NET 6.0 Feature API
  tags:
    - service
    - template
    - feature-api
spec:
  owner: Team Platform
  type: api
  parameters:
    - title: Enter values
      required:
        - name
        - description
        - owner
        - organization
      properties:
        name:
          title: Name
          type: string
          pattern: ^[a-z][a-z0-9]+$
          description: Unique name of the Feature API. Should be a single lowercase word and start with a letter.
          minLength: 5
          maxLength: 30
          ui:autoFocus: true
        description:
          title: Description
          type: string
          description: Description of the Feature API.
          minLength: 5
          maxLength: 300
          ui:options:
            rows: 3
          ui:widget: textarea
        owner:
          title: Owner
          type: string
          description: Owner of the package
          ui:field: OwnerPicker
          ui:widget: select
          ui:options:
            allowedKinds:
              - Group
        organization:
          title: GitHub organization
          description: The organization / owner in GitHub
          type: string
          default: fundarealestate

  # scaffolding steps
  steps:
    - id: fetch-base
      name: Fetch Template
      action: fetch:template
      input:
        url: './template'
        values:
          namespace: ${{ parameters.name }}
          name: ${{ parameters.name }}
          repoName: '${{ parameters.name }}.funda.io'
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Create GitHub Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        defaultBranch: main
        description: ${{ parameters.description }}
        repoUrl: 'github.com?owner=${{ parameters.organization }}&repo=${{ parameters.name }}.funda.io'

    - id: azdevops
      name: Create Azure DevOps Pipeline
      action: azdevops-pipeline-creator
      input:
        owner: ${{ parameters.owner }}
        name: '${{ parameters.name }}.funda.io'

    - id: updateCatalogInfo
      name: Update Catalog Entity Descriptor
      action: catalog:write
      input:
        entity:
          $yaml: template/catalog-info.yaml
    - id: makepr
      name: Create GitHub Pull Request
      action: publish:github:pull-request
      input:
        description: ${{ parameters.description }}
        repoUrl: 'github.com?owner=${{ parameters.organization }}&repo=${{ parameters.name }}.funda.io'
        branchName: catalog-info
        title: "Update catalog-info.yaml"

    - id: register
      name: Register with Software Catalog
      action: catalog:register
      input:
        catalogInfoUrl: '${{ steps.publish.output.repoContentsUrl }}/catalog-info.yaml'

  # outputs
  output:
    links:
      - title: Approve PR for Catalog Entity Descriptor
        url: ${{ steps.makepr.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
